In [ ]:
# Import the dataset after text processing of comments/reviews
import pandas as pd
filter_df = pd.read_csv('short_clean_comments_df.csv')
filter_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1621463 entries, 0 to 1621462
Data columns (total 5 columns):
 #   Column         Non-Null Count    Dtype
---  ------         --------------    -----
 0   work           1621463 non-null  int64
 1   user           1621463 non-null  object
 2   stars          1357973 non-null  float64
 3   time           1621463 non-null  object
 4   clean_comment  1621463 non-null  object
dtypes: float64(1), int64(1), object(3)
memory usage: 61.9+ MB

In [ ]:
# Library to detect languages used in the comments
!pip install langdetect

Collecting langdetect
  Downloading langdetect-1.0.9.tar.gz (981 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 981.5/981.5 kB 8.5 MB/s eta 0:00:0000:0100:01
  Preparing metadata (setup.py) ... done
Requirement already satisfied: six in /opt/anaconda3/lib/python3.11/site-packages (from langdetect) (1.16.0)
Building wheels for collected packages: langdetect
  Building wheel for langdetect (setup.py) ... done
  Created wheel for langdetect: filename=langdetect-1.0.9-py3-none-any.whl size=993224 sha256=759708b821876da8910a7fd18934992844ecc6d96add005529d27dd966520ab9
  Stored in directory: /Users/admin/Library/Caches/pip/wheels/0a/f2/b2/e5ca405801e05eb7c8ed5b3b4bcf1fcabcd6272c167640072e
Successfully built langdetect
Installing collected packages: langdetect
Successfully installed langdetect-1.0.9

In [ ]:
from langdetect import detect

def detect_language(text):
    try:
        return detect(text)
    except:
        return "unknown"

filter_df['language'] = filter_df['clean_comment'].apply(detect_language)
language_counts = filter_df['language'].value_counts()
print(language_counts)

language
en         1483589
nl           24592
fr           21394
es           19216
it           15075
de           11633
da            6098
sv            5758
af            5257
no            4145
ca            4042
pt            3991
fi            2982
ro            1703
cy            1484
tl            1255
pl            1159
so            1155
id            1055
sl             987
et             874
sk             866
hu             603
lt             543
cs             475
tr             360
hr             350
sw             281
sq             260
lv             164
vi             115
unknown          2
Name: count, dtype: int64

In [ ]:
# Get the top 6 languages by frequency
top_6_languages = filter_df['language'].value_counts().head(6).index.tolist()

# Filter rows for top 6 languages
filtered_df = filter_df[filter_df['language'].isin(top_6_languages)]

# Display the filtered DataFrame
filtered_df.info()

# Save the filtered DataFrame to a CSV file
filtered_df.to_csv('filtered_top_6_languages.csv', index=False)

filtered_df

<class 'pandas.core.frame.DataFrame'>
Index: 1575499 entries, 0 to 1621462
Data columns (total 6 columns):
 #   Column         Non-Null Count    Dtype
---  ------         --------------    -----
 0   work           1575499 non-null  int64
 1   user           1575499 non-null  object
 2   stars          1325457 non-null  float64
 3   time           1575499 non-null  object
 4   clean_comment  1575499 non-null  object
 5   language       1575499 non-null  object
dtypes: float64(1), int64(1), object(4)
memory usage: 84.1+ MB

,work,user,stars,time,clean_comment,language
0,73960,Elizabeth.Wong98,4.5,"Mar 21, 2012",every evening the brave queen of persia shahra...,en
1,69413,rivkat,3.0,"Sep 20, 2009",its the school year and edward zanni of hobok...,en
2,9523995,suz.haugland,4.0,"Mar 12, 2011",i became privy to this book when another autho...,en
3,11243828,CandyH,4.0,"Feb 12, 2012",this is a tremendous story of a freed woman an...,en
4,9071901,miyurose,2.0,"Jul 12, 2010",and with this book i am officially caught up w...,en
...,...,...,...,...,...,...
1621458,11633344,TheLogo,4.5,"Aug 25, 2011",i came to this book with low expectations the ...,en
1621459,129503,evementen,NaN,"Jan 29, 2012",this is quite possibly the cutest kids book iv...,en
1621460,11749693,AmyMacEvilly,5.0,"Mar 31, 2013",this is a fairy tale which is very much a cupi...,en
1621461,9705446,bibliosa,NaN,"Nov 22, 2011",despus del extraordinario xito de los ojos ama...,es
1621462,32396,jlelliott,4.0,"Aug 31, 2007",i originally met most of the diseases covered ...,en

In [ ]:
df_all = pd.read_csv('filtered_top_6_languages.csv')
df_all.info()

df_all.nunique()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1575499 entries, 0 to 1575498
Data columns (total 6 columns):
 #   Column         Non-Null Count    Dtype
---  ------         --------------    -----
 0   work           1575499 non-null  int64
 1   user           1575499 non-null  object
 2   stars          1325457 non-null  float64
 3   time           1575499 non-null  object
 4   clean_comment  1575499 non-null  object
 5   language       1575499 non-null  object
dtypes: float64(1), int64(1), object(4)
memory usage: 72.1+ MB

work              456159
user               78623
stars                 10
time                2920
clean_comment    1538680
language               6
dtype: int64

In [ ]:
df_all['language'].value_counts()

language
en    1483589
nl      24592
fr      21394
es      19216
it      15075
de      11633
Name: count, dtype: int64

In [ ]:
# Drop duplicate rows based on 'clean_comment' column
df_cleaned = df_all.drop_duplicates(subset='clean_comment', keep='first')

# Display the shape of the cleaned DataFrame
print(f"Original DataFrame shape: {df_all.shape}")
print(f"Cleaned DataFrame shape: {df_cleaned.shape}")

# Save to CSV
csv_file_path = "full_cleaned.csv"
df_cleaned.to_csv(csv_file_path, index=False)

Original DataFrame shape: (1575499, 6)
Cleaned DataFrame shape: (1538680, 6)

In [ ]:
df_all = pd.read_csv('full_cleaned.csv')
df_all.info()

df_all.nunique()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1538680 entries, 0 to 1538679
Data columns (total 6 columns):
 #   Column         Non-Null Count    Dtype
---  ------         --------------    -----
 0   work           1538680 non-null  int64
 1   user           1538680 non-null  object
 2   stars          1298896 non-null  float64
 3   time           1538680 non-null  object
 4   clean_comment  1538680 non-null  object
 5   language       1538680 non-null  object
dtypes: float64(1), int64(1), object(4)
memory usage: 70.4+ MB

work              446821
user               78055
stars                 10
time                2920
clean_comment    1538680
language               6
dtype: int64

## Sentiment analysis with textblob

In [ ]:
import pandas as pd
from textblob import TextBlob
import time

# Sentiment Analysis with 5 Scores
def get_sentiment_label_and_score(text):
    analysis = TextBlob(text)
    polarity = analysis.sentiment.polarity  # Actual polarity value (-1 to 1)

    # Define sentiment categories
    if polarity > 0.6:
        sentiment_label, sentiment_score = "Extremely Positive", 5.0
    elif polarity > 0:
        sentiment_label, sentiment_score = "Positive", 4.0
    elif polarity == 0:
        sentiment_label, sentiment_score = "Neutral", 3.0
    elif polarity > -0.6:
        sentiment_label, sentiment_score = "Negative", 2.0
    else:
        sentiment_label, sentiment_score = "Extremely Negative", 1.0

    return sentiment_label, sentiment_score, (polarity + 1)/2

start_time = time.time()
df_all[['sentiment_label_textblob_no_translate', 'sentiment_score_textblob_no_translate','polarity_textblob_no_translate' ]] = df_all['clean_comment'].apply(
    lambda x: pd.Series(get_sentiment_label_and_score(x))
)
end_time = time.time()
print(f"Time for sentiment analysis with textblob of all comments with no translation: {end_time - start_time:.2f} seconds")

In [ ]:
df_all.to_csv('full_cleaned_textblob', index=False)

In [ ]:
import pandas as pd

textblob_df = pd.read_csv('full_cleaned_textblob')
textblob_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1538680 entries, 0 to 1538679
Data columns (total 9 columns):
 #   Column                                 Non-Null Count    Dtype
---  ------                                 --------------    -----
 0   work                                   1538680 non-null  int64
 1   user                                   1538680 non-null  object
 2   stars                                  1298896 non-null  float64
 3   time                                   1538680 non-null  object
 4   clean_comment                          1538680 non-null  object
 5   language                               1538680 non-null  object
 6   sentiment_label_textblob_no_translate  1538680 non-null  object
 7   sentiment_score_textblob_no_translate  1538680 non-null  float64
 8   polarity_textblob_no_translate         1538680 non-null  float64
dtypes: float64(3), int64(1), object(5)
memory usage: 105.7+ MB

In [ ]:
# Calculate the correlation between 'stars' and 'sentiment_score_textblob_no_translate'
correlation = textblob_df[['stars', 'sentiment_score_textblob_no_translate']].corr()

# Print the correlation matrix
print(correlation)

# Pearson correlation value between the two columns
pearson_corr = correlation.loc['stars', 'sentiment_score_textblob_no_translate']
print(f"Pearson correlation between actual stars and Textblob-generated stars: {pearson_corr}")

                                          stars  \
stars                                  1.000000
sentiment_score_textblob_no_translate  0.199906

                                       sentiment_score_textblob_no_translate
stars                                                               0.199906
sentiment_score_textblob_no_translate                               1.000000
Pearson correlation between actual stars and Textblob-generated stars: 0.19990597731292578
                                   stars  polarity_textblob_no_translate
stars                           1.000000                        0.241048
polarity_textblob_no_translate  0.241048                        1.000000
Pearson correlation between actual stars and Textblob-generated stars: 0.24104792896728466